# Generated by Django 5.1.6 on 2025-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participant_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_approved',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
