# Generated by Django 5.1.6 on 2025-04-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sponsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
